// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! Topology TOML signature verification — RFC-0005 + RFC-0011.
//!
//! Each signed file ships with a `.SIG` sidecar that shares its BASE name
//! (`CAPS.TOM` + `CAPS.SIG`, `CONFIG.INI` + `CONFIG.SIG`) and holds a single
//! Ed25519 signature over the raw file bytes. `SCHED.TOM` has none since wave
//! 15: the signed `CAPS.TOM` binds it by its SHA-256 (`crate::signed`). Not `<file>.SIG`: a two-dot name is not a FAT 8.3 short name and
//! the kernel's FAT32 driver cannot open it — see [`crate::paths`].
//!
//! The trusted public key lives in OTP / eFuse on real hardware (RFC-0011)
//! and in a compile-time constant for QEMU / dev builds.
//!
//! On boot:
//!
//! ```text
//!     verify_signature(&toml_bytes, &sig, &TRUSTED_PUBKEY)?;
//! ```
//!
//! Failure ⇒ kernel halts before parsing.

use azos_crypto::ed25519::{
    sig_verify_message, ED25519_PUBLIC_KEY_SIZE, ED25519_SIGNATURE_SIZE,
};

// Generated by `build.rs` from `tools/keys/test_pub.bin` (override with
// env `TOPOLOGY_PUBKEY_PATH`) — see that file's doc comment. Defines
// `TRUSTED_PUBKEY_BYTES: [u8; 32]`, re-exported below with the doc comment
// the crate's `#![deny(missing_docs)]` requires (the generated file itself
// carries none).
#[allow(missing_docs)]
mod generated_pubkey {
    include!(concat!(env!("OUT_DIR"), "/topology_pubkey.rs"));
}

/// The Ed25519 public key that `.SIG` sidecars (`CAPS.SIG` and — as of
/// W2-B5 — `CONFIG.SIG`) are verified
/// against. Embedded at compile time from `tools/keys/test_pub.bin` by
/// `build.rs` (override with env `TOPOLOGY_PUBKEY_PATH`); all-zero if no
/// key file was found, which makes every signature check fail closed.
pub const TRUSTED_PUBKEY: [u8; ED25519_PUBLIC_KEY_SIZE] = generated_pubkey::TRUSTED_PUBKEY;

/// Errors returned by [`verify_signature`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum VerifyError {
    /// Signature buffer is the wrong length (must be 64 bytes).
    BadSignatureLen,
    /// Trusted-key buffer is the wrong length (must be 32 bytes).
    BadKeyLen,
    /// Cryptographic verification failed.
    InvalidSignature,
    /// Not returned since wave 15: the caller's buffer bounds the payload
    /// (`verify_signature` has no size limit of its own). Kept for the ABI
    /// of the error type.
    PayloadTooLarge,
}

/// Verify an Ed25519 signature over a TOML byte slice.
///
/// `toml_bytes`     — the raw bytes of `CAPS.TOML` or `SCHED.TOML`.
/// `signature`      — exactly 64 bytes from the `.SIG` sidecar.
/// `trusted_pubkey` — exactly 32 bytes; production = OTP-anchored key.
///
/// # Ordering contract for whoever wires the loader
///
/// This function is **real** verification, not a stub: `sig_verify_message`
/// in `crates/core/crypto/src/ed25519.rs` runs `verify_strict` against the
/// supplied key. The loader is `crate::signed::fill_signed` (wave 15), which
/// the kernel calls at boot under Kconfig `TOPOLOGY_SOURCE`.
///
/// The loader MUST call `verify_signature` on the raw bytes **before**
/// handing them to `parse_*`, and refuse on error.
/// The order is the whole point: the parser is a byte-level state
/// machine fed straight from an attacker-writable FAT32 partition, and
/// parsing first would expose it to unsigned input — every parser bug
/// (and F3's unterminated-array hang was one) becomes reachable by
/// anyone who can write the SD card. Verify, then parse, then admit.
/// Do not "optimise" this by parsing to find the signature: the
/// signature lives in a separate `.SIG` sidecar precisely so that no
/// part of the signed payload has to be interpreted before the
/// signature over it has been checked.
pub fn verify_signature(
    toml_bytes: &[u8],
    signature: &[u8],
    trusted_pubkey: &[u8],
) -> Result<(), VerifyError> {
    if signature.len() != ED25519_SIGNATURE_SIZE {
        return Err(VerifyError::BadSignatureLen);
    }
    if trusted_pubkey.len() != ED25519_PUBLIC_KEY_SIZE {
        return Err(VerifyError::BadKeyLen);
    }
    let mut sig_buf = [0u8; ED25519_SIGNATURE_SIZE];
    sig_buf.copy_from_slice(signature);
    let mut key_buf = [0u8; ED25519_PUBLIC_KEY_SIZE];
    key_buf.copy_from_slice(trusted_pubkey);

    // No size bound here: every caller reads into a bounded buffer (the
    // topology's Kconfig `TOPOLOGY_*_MAX_KB`, CONFIG.INI's 1 KiB, the ML
    // service's), and `sig_verify`'s 4 KiB bound of the raw primitive refused
    // a valid CAPS.TOM of 4.6 KB (wave 15).
    if sig_verify_message(&key_buf, &sig_buf, toml_bytes) {
        Ok(())
    } else {
        Err(VerifyError::InvalidSignature)
    }
}

// ── CONFIG.SIG format v2 (RFC-0054 finding 7, wave 11) ──────────────────────
//
// A bare signature over CONFIG.INI's bytes (the v1 sidecar, what
// `verify_signature` checks) can be replayed: an older, validly signed
// CONFIG.INI — one with `link_encrypt` off or an OTA listener port set — copied
// back onto the device, or onto any device that shares the key, verifies. v2
// binds the signature to ONE device and to a counter the kernel never lets go
// backwards (the floor in the device record, `crate::device_record`).

/// Magic of a `CONFIG.SIG` v2 sidecar.
pub const CONFIG_SIG_MAGIC: [u8; 4] = *b"KCFG";
/// Version byte of the only sidecar format this kernel accepts.
pub const CONFIG_SIG_VERSION: u8 = 2;
/// Bytes of a v2 sidecar: magic, version, 3 zero bytes, device id, counter,
/// signature.
pub const CONFIG_SIG_V2_LEN: usize = 4 + 1 + 3 + crate::device_record::DEVICE_ID_LEN + 8 + ED25519_SIGNATURE_SIZE;
/// Domain tag the signed message starts with, so a v2 signature can never be
/// read as a signature over some other kind of message under the same key.
pub const CONFIG_SIG_DOMAIN: [u8; 16] = *b"AZOS-CFG-SIG-v02";
/// Bytes of the signed message: domain, device id, counter, SHA-256 of the file.
pub const CONFIG_SIG_MESSAGE_LEN: usize = 16 + crate::device_record::DEVICE_ID_LEN + 8 + 32;

/// Why a `CONFIG.SIG` was not accepted.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ConfigSigError {
    /// A bare 64-byte signature: the replayable v1 format, refused.
    V1Format,
    /// Wrong length, magic, version, non-zero padding, or counter 0.
    BadFormat,
    /// Well formed, but bound to another device's id.
    WrongDevice,
    /// The signature does not verify against the trusted key.
    InvalidSignature,
}

/// The message a v2 `CONFIG.SIG` signs: `domain ‖ device id ‖ counter (LE) ‖
/// SHA-256(ini)`. Fixed size, so the file itself is never copied.
pub fn config_sig_message(
    device_id: &[u8; crate::device_record::DEVICE_ID_LEN],
    counter: u64,
    ini: &[u8],
) -> [u8; CONFIG_SIG_MESSAGE_LEN] {
    let mut m = [0u8; CONFIG_SIG_MESSAGE_LEN];
    let id = crate::device_record::DEVICE_ID_LEN;
    m[..16].copy_from_slice(&CONFIG_SIG_DOMAIN);
    m[16..16 + id].copy_from_slice(device_id);
    m[16 + id..24 + id].copy_from_slice(&counter.to_le_bytes());
    m[24 + id..].copy_from_slice(&azos_crypto::sha256::sha256(ini));
    m
}

/// Check a `CONFIG.SIG` v2 sidecar over `ini` for THIS device: the counter it
/// signs on success. The caller compares it with the floor; this function
/// knows nothing about the floor.
///
/// The device id is compared before the signature is verified, and the
/// signature is verified over OUR id, not over the one the sidecar carries,
/// so a sidecar can never name a device it was not signed for.
pub fn verify_config_sig_v2(
    ini: &[u8],
    sidecar: &[u8],
    device_id: &[u8; crate::device_record::DEVICE_ID_LEN],
    trusted_pubkey: &[u8],
) -> Result<u64, ConfigSigError> {
    if sidecar.len() == ED25519_SIGNATURE_SIZE {
        return Err(ConfigSigError::V1Format);
    }
    if sidecar.len() != CONFIG_SIG_V2_LEN
        || sidecar[..4] != CONFIG_SIG_MAGIC
        || sidecar[4] != CONFIG_SIG_VERSION
        || sidecar[5..8] != [0, 0, 0]
    {
        return Err(ConfigSigError::BadFormat);
    }
    let id = crate::device_record::DEVICE_ID_LEN;
    let mut c = [0u8; 8];
    c.copy_from_slice(&sidecar[8 + id..16 + id]);
    let counter = u64::from_le_bytes(c);
    if counter == 0 {
        return Err(ConfigSigError::BadFormat);
    }
    if sidecar[8..8 + id] != device_id[..] {
        return Err(ConfigSigError::WrongDevice);
    }
    let msg = config_sig_message(device_id, counter, ini);
    match verify_signature(&msg, &sidecar[16 + id..], trusted_pubkey) {
        Ok(()) => Ok(counter),
        Err(_) => Err(ConfigSigError::InvalidSignature),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bad_signature_len_rejected() {
        let toml = b"[task.a]\ncaps = []\n";
        let key = [0u8; ED25519_PUBLIC_KEY_SIZE];
        let too_short = [0u8; 32];
        assert_eq!(
            verify_signature(toml, &too_short, &key),
            Err(VerifyError::BadSignatureLen)
        );
    }

    #[test]
    fn bad_key_len_rejected() {
        let toml = b"x";
        let sig = [0u8; ED25519_SIGNATURE_SIZE];
        let bad_key = [0u8; 16];
        assert_eq!(
            verify_signature(toml, &sig, &bad_key),
            Err(VerifyError::BadKeyLen)
        );
    }

    #[test]
    fn zero_signature_does_not_validate() {
        // A zero signature against random data should not validate.
        let toml = b"[task.a]\ncaps = []\n";
        let sig = [0u8; ED25519_SIGNATURE_SIZE];
        let key = [0u8; ED25519_PUBLIC_KEY_SIZE];
        assert_eq!(
            verify_signature(toml, &sig, &key),
            Err(VerifyError::InvalidSignature)
        );
    }
}
