// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! Host stand-in for `azos_limits`.
//!
//! **WHY this exists.** The real crate is generated by a `build.rs` that
//! parses the repository's `.config` and pulls `azos-config` and `sha2`
//! from the registry. This suite is excluded from the workspace and has a
//! path-only `Cargo.lock`; making it fetch a registry crate to learn one
//! integer would be a network dependency in a host test.
//!
//! **Why the exact value does not matter.** `vfs.rs` re-exports this as
//! `MAX_FDS`, whose only use is the width of the machine-wide [`FdTable`].
//! The tests here open their files through `ScratchFds` (`SCRATCH_FDS = 8`,
//! a constant of `vfs.rs` itself), so nothing they assert depends on this
//! number. It is kept at the same order of magnitude as the shipped
//! configurations so a table of this width is still cheap to allocate.
pub const MAX_FDS_PER_PROC: usize = 16;

/// The real `nospec.rs` (Spectre v1 index masking), pulled by `#[path]` so
/// `vfs.rs` masks with the same code the kernel runs (the host takes its
/// portable branch). On, as the shipped default is.
pub const MITIGATION_SPECTRE_V1_INDEX: bool = true;
#[path = "../../../../../../crates/core/limits/src/nospec.rs"]
pub mod nospec;

/// `vfs.rs` and `tmpfs.rs` size their tables from these (Kconfig
/// `VFS_MAX_FILES`, `VFS_MAX_MOUNTS`, `TMPFS_MAX_FILES`, `TMPFS_MAX_KB`).
/// The shipped defaults, so the tests that fill a table fill the same one.
pub const VFS_MAX_FILES: usize = 128;
pub const VFS_MAX_MOUNTS: usize = 4;
pub const TMPFS_MAX_FILES: usize = 64;
pub const TMPFS_MAX_KB: usize = 2048;
/// Kconfig `FS_BLOCK_CACHE_KB` (fat32.rs's sector cache): embedded's 64,
/// the smallest shipped cache that is not the 4 KiB legacy one. It holds the
/// fixture volume's working set, so the tests that assert "served from RAM"
/// assert it at a size a 16 MiB board ships with.
pub const FS_BLOCK_CACHE_KB: usize = 64;
/// config/Kconfig.arch `PAGE_SHIFT` (procfs' meminfo scales page counts by it):
/// 4 KiB, the value every host build models.
pub const PAGE_SHIFT: usize = 12;
