[package]
name = "azos_service"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR GPL-2.0-only"
publish = false

[dependencies]
azos_ipc = { workspace = true }
azos_sched = { workspace = true }
azos_sync = { workspace = true }
azos_common = { workspace = true }
azos_limits = { workspace = true }
