// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! Linker-script parameters for the translation granule.
//!
//! `kernel/linker-aarch64.ld` aligns every output section to a page (W^X
//! remaps whole pages, so `.text` and `.rodata` must not share one) and
//! links the kernel `KERNEL_VA_OFFSET` above its load address. Both depend
//! on the granule the cargo features `page-16k` / `page-64k` select
//! (config/Kconfig.arch `AARCH64_PAGE_*`; neither = 4 KiB). A linker script
//! cannot read a cargo feature, so this writes them into
//! `$OUT_DIR/azos_granule.ld`, which the script `INCLUDE`s through the
//! search path added below.
//!
//! The values are not trusted on their own: the script ASSERTs both against
//! absolute symbols `boot.S` emits from Rust's own constants
//! (`_azos_page_size_check`, `_kernel_va_offset_check`), so if this file
//! and `crates/core/arch-aarch64/src/mmu.rs` ever disagree the kernel fails
//! to link. The riscv64 linker scripts do not include the file.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let f16 = env::var_os("CARGO_FEATURE_PAGE_16K").is_some();
    let f64 = env::var_os("CARGO_FEATURE_PAGE_64K").is_some();
    if f16 && f64 {
        panic!("kernel features `page-16k` and `page-64k` are exclusive (Kconfig AARCH64_PAGE_* is a choice)");
    }
    // Page size and input range, mirroring arch-aarch64's `Granule` table:
    // 4 KiB and 16 KiB walk three levels at 39 bits, 64 KiB needs 48.
    let (page, va_bits): (u64, u32) = if f64 {
        (65536, 48)
    } else if f16 {
        (16384, 39)
    } else {
        (4096, 39)
    };
    let offset: u64 = !((1u64 << va_bits) - 1);
    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let text = format!(
        "/* Generated by kernel/build.rs from the cargo features page-16k/page-64k. */\n\
         AZOS_PAGE_SIZE = {page:#x};\n\
         KERNEL_VA_OFFSET_LITERAL = {offset:#x};\n"
    );
    let path = out.join("azos_granule.ld");
    // Rewrite only on change, so an unchanged granule does not relink.
    if fs::read_to_string(&path).ok().as_deref() != Some(text.as_str()) {
        fs::write(&path, text).expect("write azos_granule.ld");
    }
    println!("cargo:rustc-link-search=native={}", out.display());
    println!("cargo:rerun-if-changed=build.rs");
}
