// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! `SYS_MODULE_VERIFY` (630) and `SYS_MODULE_MAP_X` (631): the kernel half of
//! loading a relocatable module into a ring-3 server (RFC-0053 6.1, stage
//! L0b). Compiled only with the `lx-loader` feature (Kconfig
//! `LINUX_DRIVERS` + `LX_SERVER_SKELETON`); without it both numbers are
//! unassigned.
//!
//! Two rules in this tree forbid the obvious loader: `sys_mmap` refuses
//! `PROT_EXEC` and there is no `mprotect` (W^X by construction), and every
//! executable is bound at exec to a SHA-256 the build computed. A module read
//! from the boot volume is new code inside an already-running process, so
//! neither rule covers it unless the kernel is asked. The reconciliation:
//!
//! 1. The server hands the module FILE bytes to `SYS_MODULE_VERIFY`. The
//!    kernel hashes them and looks the name up in [`MODULE_SHA256`], the
//!    table `tools/module_hashes.py` generates into the kernel image (the
//!    secure-boot-signed artefact). On a match it grants a one-shot token
//!    bound to the caller's TID and to the module's length; otherwise the
//!    refusal is RECORDED (a count, [`module_refusals`], and a console line).
//! 2. The server relocates the module into its own anonymous memory
//!    (`crates/core/lx-loader`), then calls `SYS_MODULE_MAP_X` with the
//!    token and the text range. The kernel consumes the token, checks the
//!    range (at most the verified length rounded up to a page; every page
//!    the caller's own private read-write page) and flips it read-write ->
//!    read-execute in one PTE update per page (`vmm::set_user_range_exec`).
//!    Nothing is ever writable and executable at once.
//!
//! **Residual risk, accepted in RFC-0053 6.1.** The digest covers the input
//! bytes, not the relocated text: a server that is already compromised can
//! write any code into the range between steps 1 and 2. The bound on the
//! range is what limits it to one module's worth of pages per verification.
//! Relocating in the kernel instead would put a relocation engine that parses
//! untrusted input in S-mode, which RFC-0040 rule 3 rules out.

use core::sync::atomic::{AtomicU32, Ordering};

use azos_abi::error::Errno;
use azos_abi::syscall_nr::MODULE_MAX_BYTES;
use azos_drv_sys::kprintln;
use azos_arch::{ArchPlatform, ARCH};

// `MODULE_SHA256: &[(&str, [u8; 32])]`, generated by `tools/module_hashes.py`
// (`make lx-modules`). One table per ISA: the module is compiled for one.
#[cfg(target_arch = "riscv64")]
include!("../../../../build/module_hashes.rs"); // missing? run `make build/module_hashes.rs` in the repo root
#[cfg(target_arch = "aarch64")]
include!("../../../../build/module_hashes_aarch64.rs"); // missing? run `make build/module_hashes_aarch64.rs`
#[cfg(not(any(target_arch = "riscv64", target_arch = "aarch64")))]
include!("../../../../build/module_hashes.rs"); // host builds: the riscv64 table

/// Longest 8.3 module name (`NAME1234.KO` is 11; one spare).
const NAME_MAX: usize = 12;
/// Live tokens at once (Kconfig `LX_MODULE_TOKENS`). A server verifies and
/// maps one module at a time; the default four lets a few servers start in
/// parallel without one evicting another's.
const SLOTS: usize = azos_limits::LX_MODULE_TOKENS;

static TOKENS: azos_sync::SpinLock<crate::module_tokens::Tokens<SLOTS>> =
    azos_sync::SpinLock::new(crate::module_tokens::Tokens::new());
static NONCE: AtomicU32 = AtomicU32::new(0x4c58_0001);
static REFUSALS: AtomicU32 = AtomicU32::new(0);
static GRANTS: AtomicU32 = AtomicU32::new(0);
static MAPPED: AtomicU32 = AtomicU32::new(0);

/// Task `tid` has exited: its unused tokens go with it (the exit hook,
/// `kernel/src/boot/sched.rs`). Returns how many were dropped.
pub fn module_tokens_release(tid: u32) -> usize {
    TOKENS.lock().release_all(tid)
}

/// Verification refusals since boot (digest or name not in the table).
pub fn module_refusals() -> u32 {
    REFUSALS.load(Ordering::Relaxed)
}
/// Tokens granted since boot.
pub fn module_grants() -> u32 {
    GRANTS.load(Ordering::Relaxed)
}
/// Successful `SYS_MODULE_MAP_X` calls since boot.
pub fn module_mappings() -> u32 {
    MAPPED.load(Ordering::Relaxed)
}

fn err(e: Errno) -> i64 {
    e.to_syscall_ret()
}

/// `SYS_MODULE_VERIFY`: see `azos_abi::syscall_nr::SYS_MODULE_VERIFY`.
pub fn sys_module_verify(buf: u64, len: u64, name_ptr: u64, name_len: u64) -> i64 {
    if len == 0 || len > MODULE_MAX_BYTES || name_len == 0 || name_len as usize > NAME_MAX {
        return err(Errno::EINVAL);
    }
    let mut name = [0u8; NAME_MAX];
    let name_len = name_len as usize;
    if !azos_sched::process::copy_from_user(name.as_mut_ptr(), name_ptr as usize, name_len) {
        return err(Errno::EFAULT);
    }
    let name = &name[..name_len];

    // Hash straight from user memory in bounded chunks: no kernel buffer the
    // size of the module, and an unreadable page anywhere fails the call.
    let mut h = azos_crypto::sha256::Sha256::new();
    let mut chunk = [0u8; 256];
    let mut done = 0u64;
    while done < len {
        let n = (len - done).min(chunk.len() as u64) as usize;
        if !azos_sched::process::copy_from_user(chunk.as_mut_ptr(), (buf + done) as usize, n) {
            return err(Errno::EFAULT);
        }
        h.update(&chunk[..n]);
        done += n as u64;
    }
    let digest = h.finalize();
    let tid = azos_sched::current_task_tid();

    let row = MODULE_SHA256.iter().find(|(n, _)| n.as_bytes() == name);
    match row {
        Some((_, d)) if d[..] == digest[..] => {}
        // Gate canary: a listed name is enough. `lx: module tamper refused`
        // must go red with this on.
        #[cfg(feature = "lx-verify-canary")]
        Some(_) => {}
        _ => {
            let prior = REFUSALS.fetch_add(1, Ordering::Relaxed);
            // The console line for the first few only: a ring-3 loop must not
            // flood the UART. The counter keeps every one.
            if prior < 8 {
                let why = if row.is_some() { "digest not in the table" } else { "no table entry" };
                azos_drv_sys::kwarn!(
                    "[LX] module verify REFUSED: tid {} {} sha256 {:02x}{:02x}{:02x}{:02x}... {} (refusal {} RECORDED)",
                    tid, core::str::from_utf8(name).unwrap_or("?"),
                    digest[0], digest[1], digest[2], digest[3], why, prior + 1
                );
            }
            return err(Errno::EPERM);
        }
    }

    let page = azos_arch::PAGE_SIZE as u64;
    let max_pages = len.div_ceil(page) as usize;
    let nonce = NONCE.fetch_add(0x9e37_79b9, Ordering::Relaxed) | 1;
    let slot = TOKENS.lock().grant(tid, nonce, max_pages);
    GRANTS.fetch_add(1, Ordering::Relaxed);
    kprintln!(
        "[LX] module verified: tid {} {} sha256 {:02x}{:02x}{:02x}{:02x}... ({} bytes, up to {} pages executable)",
        tid, core::str::from_utf8(name).unwrap_or("?"),
        digest[0], digest[1], digest[2], digest[3], len, max_pages
    );
    // Positive, and never 0: slot index in the high half, nonce (odd) below.
    ((((slot as u64) + 1) << 32) | nonce as u64) as i64
}

/// `SYS_MODULE_MAP_X`: see `azos_abi::syscall_nr::SYS_MODULE_MAP_X`.
pub fn sys_module_map_x(token: u64, addr: u64, len: u64) -> i64 {
    let tid = azos_sched::current_task_tid();
    let slot = (token >> 32) as usize;
    let nonce = token as u32;
    // One attempt per verification, whatever happens below.
    let Some(max_pages) = TOKENS.lock().take(slot, tid, nonce) else {
        return err(Errno::EPERM);
    };
    let page = azos_arch::PAGE_SIZE as u64;
    if len == 0 || addr % page != 0 {
        return err(Errno::EINVAL);
    }
    let pages = len.div_ceil(page);
    if pages > max_pages as u64 {
        azos_drv_sys::kwarn!("[LX] module map_x REFUSED: tid {} asked for {} pages, the token allows {}", tid, pages, max_pages);
        return err(Errno::EINVAL);
    }
    let Some(end) = addr.checked_add(pages * page) else { return err(Errno::EINVAL) };
    if end as usize > crate::handlers::USER_VA_TOP {
        return err(Errno::EINVAL);
    }
    let pt = azos_sched::current_user_pt();
    if pt == 0 {
        return err(Errno::EPERM);
    }
    let (shm_lo, shm_hi) = azos_sched::user_shm_window();
    match azos_mm::vmm::set_user_range_exec(pt, addr as usize, end as usize, shm_lo, shm_hi) {
        Ok(_) => {}
        Err(_) => {
            azos_drv_sys::kwarn!("[LX] module map_x REFUSED: tid {} range {:#x}+{:#x} is not the caller's own private RW memory", tid, addr, len);
            return err(Errno::EINVAL);
        }
    }
    // Read the result back through the walk the copy-to-user path uses, not
    // through the function that just wrote it: a page ring 3 can still
    // write is refused here (made inaccessible), never returned as success.
    let mut va = addr as usize;
    while va < end as usize {
        if azos_mm::vmm::user_write_would_be_permitted(pt, va) {
            azos_drv_sys::kerr!("[LX] module map_x W^X VIOLATED: tid {} page {:#x} is writable after the flip; range unmapped", tid, va);
            let mut v = addr as usize;
            while v < end as usize {
                azos_mm::vmm::unmap(pt, v);
                v += page as usize;
            }
            return err(Errno::EINVAL);
        }
        va += page as usize;
    }
    sync_icache(pt, addr as usize, end as usize);
    MAPPED.fetch_add(1, Ordering::Relaxed);
    kprintln!("[LX] module text mapped RX: tid {} {:#x}..{:#x} ({} pages, W^X read back)", tid, addr, end, pages);
    0
}

/// Make the instruction fetch of EVERY hart see the bytes the server wrote
/// through its data mapping: the task may run on any hart next.
fn sync_icache(pt: usize, start: usize, end: usize) {
    // Clean by the kernel's own alias of each frame (a PIPT D-cache: any
    // alias cleans the line) rather than by the user VA, which would put EL1
    // cache maintenance on an EL0 mapping. `icache_needs_dcache_clean` is a
    // per-ISA constant (false on riscv64): the loop folds away there.
    if ARCH.icache_needs_dcache_clean() {
        let page = azos_arch::PAGE_SIZE;
        let mut va = start;
        while va < end {
            if let Some(pa) = azos_mm::vmm::translate_user(pt, va, false) {
                let k = azos_mm::addr::phys_to_virt(pa & !(page - 1));
                // SAFETY: a whole frame of RAM through the kernel's map.
                unsafe { ARCH.dcache_clean(k, page) };
            }
            va += page;
        }
    }
    // riscv64: local `fence.i` + SBI remote fence.i to every hart;
    // aarch64: the broadcast I-cache invalidate.
    ARCH.icache_sync_all();
}
