#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Fernando Rodriguez
#
# Build the lx/ module set with Linux's Kbuild inside the pinned container
# (RFC-0053 L1; owner decision, round 49: podman on the Mac).
#
#   tools/lx_kbuild/run.sh build <outdir>   # both ISAs + the xz fixture
#   tools/lx_kbuild/run.sh image            # build the image (network: apt)
#   tools/lx_kbuild/run.sh check            # exit 0 if a build can run
#   tools/lx_kbuild/run.sh linux <outdir>   # the Linux comparison kernels
#
# `linux` (after `build` into build/lx/kbuild) builds, for both ISAs, a Linux
# kernel from the FULL pinned tree with the modules' exact configuration,
# lxbench.ko (lx/glue/bench) and an initramfs holding the same xz_dec.ko and
# XZTEST.XZ the AzOS volume carries: the "same QEMU, same .ko" baseline
# (owner rule, wave 13). The full tree is streamed with `git archive` from
# the checkout's object store (the sparse checkout is not widened).
#
# `build` exits 3 and prints "SKIP: <reason>" when it cannot run here: no
# podman, the podman machine is down, the image is not built, or no fetched
# Linux tree at the pin. LX_LINUX_SRC points at a fetched tree elsewhere
# (default third_party/linux; the iCloud checkout cannot hold one, so a gate
# run from it sets LX_LINUX_SRC to a worktree's tree).
# Every Kbuild run is --network=none and mounts the tree read-only.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
root="$(cd "$here/../.." && pwd)"
src="${LX_LINUX_SRC:-$root/third_party/linux}"
podman="${PODMAN:-podman}"
tag="azos-lx-kbuild:$(shasum -a 256 "$here/Containerfile" | cut -c1-12)"
# The upstream modules, as SYMBOL=path/in/tree.ko (the RFC 8.1 validated list).
modules=(XZ_DEC=lib/xz/xz_dec.ko)

skip() { echo "SKIP: $*"; exit 3; }

usable() {
    command -v "$podman" >/dev/null 2>&1 || skip "podman not installed"
    "$podman" info >/dev/null 2>&1 || skip "podman cannot reach its machine (podman machine start)"
}

case "${1:-}" in
image)
    usable
    "$podman" build --pull=never -t "$tag" -f "$here/Containerfile" "$here"
    {
        echo "# Generated by \`make lx-kbuild-image\` (tools/lx_kbuild/run.sh image). Do not edit."
        echo "tag=$tag"
        echo "base=$(sed -n 's/^FROM //p' "$here/Containerfile")"
        echo "platform=$("$podman" image inspect "$tag" --format '{{.Os}}/{{.Architecture}}')"
        echo "# installed packages (dpkg-query), the full set the image carries:"
        "$podman" run --rm --network=none "$tag" cat /etc/lx-kbuild-packages
    } > "$here/IMAGE"
    echo "lx-kbuild: image $tag; recorded in tools/lx_kbuild/IMAGE"
    ;;
check|build|linux)
    usable
    "$podman" image exists "$tag" || skip "image $tag not built (make lx-kbuild-image; needs the network once)"
    [ -f "$src/Makefile" ] || skip "no Linux tree at $src (tools/lx_fetch_linux.sh in a checkout outside iCloud, or set LX_LINUX_SRC)"
    pin="$(sed -n 's/^commit=//p' "$root/lx/LINUX_PIN")"
    head="$(git -C "$src" rev-parse HEAD 2>/dev/null || true)"
    [ "$head" = "$pin" ] || skip "Linux tree at $src is $head, the pin is $pin"
    [ "$1" = check ] && exit 0
    if [ "$1" = linux ]; then
        out="${2:?usage: run.sh linux <outdir>}"
        mods="$root/build/lx/kbuild"
        [ -f "$mods/SHA256SUMS" ] || { echo "run.sh linux: build the modules first (run.sh build $mods)" >&2; exit 1; }
        rm -rf "$out"; mkdir -p "$out"; out="$(cd "$out" && pwd)"
        for arch in riscv arm64; do
            git -C "$src" archive --format=tar "$pin" | "$podman" run -i --rm --network=none \
                -v "$here:/cfg:ro" -v "$root/lx/glue:/glue:ro" -v "$mods:/mods:ro" \
                -v "$root/userspace/tests/lxbench:/bench-src:ro" -v "$out:/out" "$tag" \
                sh -c 'mkdir -p /work/linux && tar -x -C /work/linux && sh /cfg/kbuild-in.sh linux "$@"' sh "$arch" "${modules[@]}"
        done
        exit 0
    fi
    out="${2:?usage: run.sh build <outdir>}"
    rm -rf "$out"; mkdir -p "$out"
    out="$(cd "$out" && pwd)"
    run() {
        "$podman" run --rm --network=none -v "$src:/src:ro" -v "$here:/cfg:ro" \
            -v "$root/lx/glue:/glue:ro" -v "$out:/out" "$tag" sh /cfg/kbuild-in.sh "$@"
    }
    run riscv "${modules[@]}"
    run arm64 "${modules[@]}"
    mv "$out/riscv" "$out/riscv64"; mv "$out/arm64" "$out/aarch64"
    python3 "$here/xz_fixture.py" > "$out/xztest.bin"
    run xz /out/xztest.bin /out/XZTEST.XZ
    # The gate's canary volume: a valid stream of a DIFFERENT plaintext (seed
    # 1), so a server that accepted any clean decode would still pass.
    python3 "$here/xz_fixture.py" 1 > "$out/xzother.bin"
    run xz /out/xzother.bin /out/XZOTHER.XZ
    (cd "$out" && shasum -a 256 riscv64/*.ko aarch64/*.ko XZTEST.XZ XZOTHER.XZ > SHA256SUMS)
    cat "$out/SHA256SUMS"
    ;;
*)
    echo "usage: $0 image | check | build <outdir>" >&2; exit 2 ;;
esac
