// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! `azos_limits` — generated compile-time constants from `.config`
//!
//! RFC-0026 Phase C2.  Every numeric, bool, and string option from the
//! Kconfig `.config` file is available here as a `pub const`.
//!
//! This crate is auto-generated by `build.rs` which reads the workspace
//! `.config` file via `azos_config::parse_config` + `emit_rust`.
//!
//! **DO NOT hand-edit the generated constants.**  Run `make menuconfig`
//! or `make defconfig-<profile>` and rebuild to change values.
//!
//! # Usage
//!
//! ```rust,ignore
//! use azos_limits::MAX_TASKS;
//! let table: [u8; MAX_TASKS] = [0; MAX_TASKS];
//! ```
//!
//! Status 2026-09-26 (V2.6): the Phase C3 migration reached PART of the
//! symbol table, not all of it. As of the 2026-09-25 audit, 78 of 167
//! declared Kconfig symbols reached no `azos_limits::` import
//! anywhere in `crates/`, `kernel/`, or `userspace/` — a same-named
//! literal twin in code (e.g. `TIMER_FREQ`, `PID_DT_MS`) made a
//! `make menuconfig` change on them look like it took effect when it did
//! not. V2.6 (this same commit) deleted those 78 from Kconfig outright
//! and wired the two whose fix was a one-line change
//! (`crates/drivers/base/src/platform.rs`, `crates/drivers/actuator/src/motor_pid.rs`);
//! `python3 tools/gen_config_index.py` lists the surviving 78 declared
//! symbols and is the place to check whether a given option is one of
//! them, not this comment. A future symbol added here without a real
//! `azos_limits::NAME` import anywhere reopens exactly this gap —
//! `crates/core/limits/build.rs` does not (yet) refuse an unimported symbol.

#![no_std]
#![allow(unused)]

// Include the file generated by build.rs into OUT_DIR.
// build.rs writes `generated.rs` during `cargo build -p azos_limits`.
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

pub mod nospec;
