#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Fernando Rodriguez
"""Write the kernel's module digest table (RFC-0053 6.1, stage L0b).

    python3 tools/module_hashes.py build/module_hashes.rs LXTEST.KO=build/lx/lxtest-riscv64.ko ...

`crates/core/syscall/src/module_ops.rs` `include!`s the output under the
`lx-loader` feature: `SYS_MODULE_VERIFY` hashes the bytes a server hands it
and grants a one-shot execute token only for a digest listed here, under the
name the server asked for. The table lives in the kernel image, which is the
secure-boot-signed artefact, so changing the module set is a kernel rebuild.

The file is rewritten only when its contents change (same rule as
userspace/image_hashes.py), so a `make` that rebuilt nothing does not make
cargo recompile the kernel. With `--check`, exits non-zero unless every
NAME=path has the digest the table lists (a gate row's pre-boot check).
"""

import hashlib
import os
import re
import sys

NAME_RE = re.compile(r"^[A-Z0-9_]{1,8}\.KO$")


def digest(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).digest()


def parse_pairs(pairs):
    rows, seen = [], set()
    skip_missing = False
    for pair in pairs:
        # Pairs after `--skip-missing` whose file does not exist are left
        # out of the table: the Kbuild modules (RFC-0053 L1) exist only when
        # `make lx-kbuild` could run, and a kernel without them must still
        # build (and then refuses them, which is the right answer).
        if pair == "--skip-missing":
            skip_missing = True
            continue
        if skip_missing and not os.path.exists(pair.partition("=")[2]):
            continue
        name, sep, path = pair.partition("=")
        if not sep or not name or not path:
            sys.exit(f"module_hashes.py: expected NAME=path, got {pair!r}")
        # FAT32 8.3: the server opens the module under this exact name.
        if not NAME_RE.match(name):
            sys.exit(f"module_hashes.py: {name!r} is not an 8.3 .KO name")
        if name in seen:
            sys.exit(f"module_hashes.py: {name} is listed twice")
        seen.add(name)
        rows.append((name, path))
    return rows


def main(argv):
    if len(argv) >= 2 and argv[1] == "--check":
        if len(argv) < 4:
            sys.exit("usage: module_hashes.py --check <table.rs> NAME=path ...")
        text = open(argv[2], encoding="utf-8").read()
        table = {m.group(1): bytes(int(b, 16) for b in m.group(2).split(","))
                 for m in re.finditer(r'\("([A-Z0-9_]+\.KO)", \[([^\]]*)\]\)', text)}
        bad = 0
        for name, path in parse_pairs(argv[3:]):
            if table.get(name) != digest(path):
                print(f"module_hashes.py: {name} ({path}) does not match {argv[2]}")
                bad += 1
        sys.exit(1 if bad else 0)
    if len(argv) < 2:
        sys.exit("usage: module_hashes.py <out.rs> NAME=path ...")
    out = argv[1]
    lines = [
        "// Generated by tools/module_hashes.py from the modules the Makefile builds.",
        "// Do not edit: `make " + out + "` rewrites it.",
        "",
        "/// `(8.3 name on the boot volume, SHA-256 of the module file)`.",
        "pub const MODULE_SHA256: &[(&str, [u8; 32])] = &[",
    ]
    for name, path in parse_pairs(argv[2:]):
        body = ", ".join(f"0x{b:02x}" for b in digest(path))
        lines.append(f"    // {path}")
        lines.append(f'    ("{name}", [{body}]),')
    lines.append("];")
    text = "\n".join(lines) + "\n"
    if os.path.exists(out) and open(out, encoding="utf-8").read() == text:
        return
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, out)


if __name__ == "__main__":
    main(sys.argv)
