// SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
// SPDX-FileCopyrightText: 2026 Fernando Rodriguez
//! WCET (Worst-Case Execution Time) instrumentation — F16.
//!
//! Provides lightweight cycle-accurate measurement of function execution time
//! using the RISC-V `rdcycle` CSR.  Tracks min, max, and average over N
//! samples per named measurement point.
//!
//! # Usage
//!
//! ```ignore
//! let t = wcet_begin();
//! // ... critical section ...
//! wcet_end(WCET_PID_LOOP, t);
//!
//! // Periodically:
//! wcet_report();   // prints table to UART
//! wcet_check_bounds();  // logs violations
//! ```
//!
//! # Design
//!
//! - All measurement points are identified by a `u8` index (named constant).
//! - Statistics are stored in a fixed-size array (no allocation).
//! - `rdcycle` is read via inline assembly — sub-microsecond resolution.
//! - On platforms without `rdcycle` (M-mode restrictions), falls back to the
//!   CLINT mtime counter with ~100ns resolution.

// ── Generated per-function WCET points (RFC-0027) ────────────────────────────
//
// `wcet_points_generated.rs` is produced by `crates/drivers/sys/build.rs` into
// `OUT_DIR`, as `crates/core/limits` does with its constants. It emits:
//   - `pub const POINT_<UPPER_SNAKE>: u8 = N;` for each annotated function
//   - `pub const WCET_FN_NAMES: &[(u8, &str, u32)]` — (id, name, budget_us)
//
// Nothing is generated into the source tree. With no `#[wcet(...)]`
// annotations the file contains only `WCET_FN_NAMES: &[] = &[];` — this
// `include!` is always valid.
include!(concat!(env!("OUT_DIR"), "/wcet_points_generated.rs"));

// ── Named measurement point IDs ──────────────────────────────────────────────

/// Maximum number of WCET measurement points.
///
/// Sourced from Kconfig option `WCET_MAX_POINTS` via `azos_limits`.
/// Profile defaults: embedded=32, edge=128, fleet=512.  Must be large
/// enough to hold the 9 fixed points plus all `#[wcet(...)]` annotations
/// enumerated by the build script.
pub use azos_limits::WCET_MAX_POINTS;

/// Measurement point: PID flight controller loop.
pub const WCET_PID_LOOP:        u8 = 0;
/// Measurement point: IMU/sensor read.
pub const WCET_SENSOR_READ:     u8 = 1;
/// Measurement point: context switch (schedule() entry → exit).
pub const WCET_CTX_SWITCH:      u8 = 2;
/// Measurement point: timer ISR handler.
pub const WCET_TIMER_ISR:       u8 = 3;
/// Measurement point: motor/ESC actuator write.
pub const WCET_ACTUATOR_WRITE:  u8 = 4;
/// Measurement point: TCP send path.
pub const WCET_NET_SEND:        u8 = 5;
/// Measurement point: CNN inference (one frame).
pub const WCET_CNN_INFER:       u8 = 6;
/// Measurement point: LiDAR scan processing.
pub const WCET_LIDAR_SCAN:      u8 = 7;
/// Measurement point: A* path planning step.
pub const WCET_PATH_PLAN:       u8 = 8;

// ── WCET bound constants (microseconds) ─────────────────────────────────────

/// Bound: PID loop must complete within 50 µs (20 kHz max rate).
pub const WCET_BOUND_PID_US:        u64 = 50;
/// Bound: sensor read within 100 µs.
pub const WCET_BOUND_SENSOR_US:     u64 = 100;
/// Bound: context switch within 5 µs.
pub const WCET_BOUND_CTX_SWITCH_US: u64 = 5;
/// Bound: timer ISR within 10 µs on real hardware.  WCET enforcement is
/// **disabled** under QEMU (`feature = "qemu"`) because the measurement is
/// not meaningful in that environment:
///
/// `read_cycles()` reads RV64 `rdcycle`, which under QEMU TCG advances at
/// the emulated 10 MHz `TIMER_FREQ`.  Under `-smp 4` TCG the emulator
/// single-threads all four virtual harts on a single host thread, so when
/// hart 0 is mid-ISR and the emulator yields to harts 1-3, `rdcycle` keeps
/// advancing — every other hart's work counts against hart 0's
/// "ISR latency".  We've measured the actual sub-step probes
/// (`vdso_update`, `wake_expired_timers`, `lease_tick`) and they total
/// ~1 ms of work, but the WCET measurement reports 88-245 ms because of
/// this TCG SMP artefact.
///
/// Enforcing a bound here therefore just produces noisy `[WCET] VIOLATION`
/// spam every tick under QEMU — without indicating any real timing issue.
/// Real WCET data is collected on VF2 / K1 hardware, where the host
/// confound does not apply.  Set the bound to `0` (= no enforcement) under
/// `feature = "qemu"`; the statistics still accumulate so `wcet_report`
/// can dump them on demand.
#[cfg(not(feature = "qemu"))]
pub const WCET_BOUND_TIMER_ISR_US:  u64 = 10;
#[cfg(feature = "qemu")]
pub const WCET_BOUND_TIMER_ISR_US:  u64 = 0;
/// Bound: actuator write within 10 µs.
pub const WCET_BOUND_ACTUATOR_US:   u64 = 10;

/// Names for the 9 fixed measurement points (IDs 0-8).
///
/// IDs 9+ are generated by `crates/drivers/sys/build.rs` and stored in
/// `WCET_FN_NAMES` (from `wcet_points_generated.rs`).
///
/// # Design choice
///
/// Rather than extending a hardcoded array to `WCET_MAX_POINTS` entries
/// (which wastes BSS for profiles with 512 slots), we use `name_of(id)`
/// which dispatches: id < 9 → fixed table, id >= 9 → linear scan of
/// `WCET_FN_NAMES`.  The linear scan is O(N_annotated) but is only
/// called from `wcet_report` / `wcet_check_bounds`, which are not hot paths.
const WCET_FIXED_NAMES: [&str; 9] = [
    "pid_loop",       // 0
    "sensor_read",    // 1
    "ctx_switch",     // 2
    "timer_isr",      // 3
    "actuator_write", // 4
    "net_send",       // 5
    "cnn_infer",      // 6
    "lidar_scan",     // 7
    "path_plan",      // 8
];

/// Return the human-readable name for a WCET measurement point.
///
/// For IDs 0-8 (fixed points) returns from `WCET_FIXED_NAMES`.
/// For IDs ≥ 9 (generated points) scans `WCET_FN_NAMES`.
/// Falls back to `"unknown"` if the ID is unregistered.
pub fn name_of(id: u8) -> &'static str {
    let idx = id as usize;
    if idx < WCET_FIXED_NAMES.len() {
        return WCET_FIXED_NAMES[idx];
    }
    // Linear scan of generated table — acceptable because this is only
    // called from the non-hot `wcet_report` and `wcet_check_bounds` paths.
    for &(gid, gname, _budget) in WCET_FN_NAMES {
        if gid == id { return gname; }
    }
    "unknown"
}

/// WCET bounds in microseconds (0 = no bound enforced).
///
/// Fixed points 0-8 are initialised directly.  Generated points (IDs ≥ 9)
/// are populated from `WCET_FN_NAMES` using a const `while` loop — stable
/// since Rust 1.79.  The array is sized to `WCET_MAX_POINTS` from Kconfig.
const WCET_BOUNDS_US: [u64; WCET_MAX_POINTS] = {
    let mut a = [0u64; WCET_MAX_POINTS];
    a[0] = WCET_BOUND_PID_US;
    a[1] = WCET_BOUND_SENSOR_US;
    a[2] = WCET_BOUND_CTX_SWITCH_US;
    a[3] = WCET_BOUND_TIMER_ISR_US;
    a[4] = WCET_BOUND_ACTUATOR_US;
    // IDs 5-8 (net_send, cnn_infer, lidar_scan, path_plan) have no bound yet
    // (left as 0 = enforcement disabled).
    // Populate generated bounds from the build-script-produced table.
    //
    // QEMU TCG SMP gating: same rationale as WCET_BOUND_TIMER_ISR_US (see
    // line 76 docs).  Under QEMU `rdcycle` is inflated 100-1000× by other-
    // hart scheduling time on the single-threaded TCG translator, so
    // enforcing a 30 / 100 µs budget on every annotated function produces
    // a flood of `[WCET] VIOLATION` spam (7000+ lines per 40s bench run,
    // saturating UART and starving wcet_report() of bandwidth — empirical
    // observation 2026-05-29).  Set generated bounds to 0 = enforcement
    // disabled under qemu.  Samples still accumulate; only the violation
    // logging path is silenced.  Real bound checks happen on VF2 / K1.
    let mut i = 0usize;
    while i < WCET_FN_NAMES.len() {
        let (id, _name, budget) = WCET_FN_NAMES[i];
        let slot = id as usize;
        if slot < WCET_MAX_POINTS {
            a[slot] = if cfg!(feature = "qemu") { 0 } else { budget as u64 };
        }
        i += 1;
    }
    a
};

// ── Statistics ────────────────────────────────────────────────────────────────

/// Per-point WCET statistics.
#[derive(Clone, Copy)]
pub struct WcetStats {
    /// Minimum observed cycle count.
    pub min_cycles:    u64,
    /// Maximum observed cycle count (WCET).
    pub max_cycles:    u64,
    /// Cumulative sum for average computation.
    pub total_cycles:  u64,
    /// Number of samples recorded.
    pub count:         u64,
    /// Number of bound violations.
    pub violations:    u32,
}

impl WcetStats {
    const fn new() -> Self {
        WcetStats {
            min_cycles:   u64::MAX,
            max_cycles:   0,
            total_cycles: 0,
            count:        0,
            violations:   0,
        }
    }

    /// Average cycles (0 if no samples).
    pub fn avg_cycles(&self) -> u64 {
        if self.count == 0 { 0 } else { self.total_cycles / self.count }
    }
}

// ── Global state (lock-free via separate u64 atomics) ─────────────────────────

use core::sync::atomic::{AtomicU64, AtomicU32, Ordering};

struct WcetTable {
    min:        [AtomicU64; WCET_MAX_POINTS],
    max:        [AtomicU64; WCET_MAX_POINTS],
    total:      [AtomicU64; WCET_MAX_POINTS],
    count:      [AtomicU64; WCET_MAX_POINTS],
    violations: [AtomicU32; WCET_MAX_POINTS],
}

// `AtomicU64`/`AtomicU32` are not Copy, so `[AtomicU64::new(0); N]` does not
// compile when N is a runtime const.  The `[const { expr }; N]` form (stable
// since Rust 1.79) evaluates the expression as a const per element, allowing
// non-Copy types.  This replaces the old `au64_arr!` / `au32_arr!` macros
// which hard-coded exactly 16 elements.

static WCET: WcetTable = WcetTable {
    min:        [const { AtomicU64::new(u64::MAX) }; WCET_MAX_POINTS],
    max:        [const { AtomicU64::new(0) };        WCET_MAX_POINTS],
    total:      [const { AtomicU64::new(0) };        WCET_MAX_POINTS],
    count:      [const { AtomicU64::new(0) };        WCET_MAX_POINTS],
    violations: [const { AtomicU32::new(0) };        WCET_MAX_POINTS],
};

// ── RISC-V cycle counter ──────────────────────────────────────────────────────

/// Read the hardware cycle counter.
///
/// `rdcycle` CSR (always available in U/S-mode when `mcounteren.CY` is set).
/// Fallback: CLINT mtime (lower resolution, ~10 MHz).
#[cfg(target_arch = "riscv64")]
#[inline(always)]
pub fn read_cycles() -> u64 {
    let cycles: u64;
    unsafe { core::arch::asm!("rdcycle {}", out(reg) cycles); }
    cycles
}

/// aarch64: no cycle counter wired up yet.
///
/// ARMv8 has a real equivalent — `PMCCNTR_EL0`, the Performance Monitors
/// Cycle Count Register — but reading it needs `PMCR_EL0`/`PMCNTENSET_EL0`
/// enabled first, and nothing in `arch-aarch64` programs the PMU yet.
/// Inventing that enable sequence from memory, unverified against real
/// hardware, is exactly what this project refuses to do for a register
/// interface (see this module's own `calibrate_cpu_freq` doc on why a wrong
/// clock constant cost every WCET figure a 375x error once already).
///
/// Returning 0 is the honest choice, not a fake reading:
/// [`calibrate_cpu_freq`] already treats a zero cycle delta as "no
/// measurement" and falls back to `CYCLES_PER_US = 1`, so WCET figures come
/// out in raw ticks instead of silently-wrong microseconds until the PMU
/// path lands.
#[cfg(not(target_arch = "riscv64"))]
#[inline(always)]
pub fn read_cycles() -> u64 {
    0
}

/// Measured CPU cycles per microsecond. 0 until [`calibrate_cpu_freq`] runs.
///
/// **This was `TIMER_FREQ`, which is a different clock.** `read_cycles` reads
/// `rdcycle` — the core's own cycle counter, running at the CPU clock — and
/// the conversion divided it by the CLINT's `mtime` timebase: 10 MHz on QEMU,
/// 4 MHz on the VF2, 24 MHz on the K1. A JH7110 core runs around 1.5 GHz, so
/// on the VF2 every WCET figure came out roughly 375x too large, and every
/// annotated budget would read as violated on hardware. The doc comment even
/// said "1 GHz on K1" while naming a constant that is 24 MHz there.
///
/// There is no CPU-frequency constant anywhere in `platform.rs` to switch to —
/// `TIMER_FREQ` and `WDT_CLK_HZ` are the only clocks the tree knows, and
/// inventing a third from memory is exactly what this project refuses to do
/// for register maps. So it is measured instead, which needs no datasheet and
/// is correct on a board nobody has characterised yet.
static CYCLES_PER_US: core::sync::atomic::AtomicU64 =
    core::sync::atomic::AtomicU64::new(0);

/// Measure the CPU clock against the CLINT timebase. Call once at boot, before
/// any WCET figure is read.
///
/// Busy-waits one hundredth of a second of `mtime` — a real wall-clock
/// interval on every board, since `TIMER_FREQ` is a DTS value — and counts
/// `rdcycle` across it. Bounded by construction: the loop exits on a `mtime`
/// comparison, so a stopped cycle counter cannot hang it, only produce a low
/// reading.
///
/// A ratio of 0 is stored as 1 rather than left at 0, so `cycles_to_us` never
/// divides by zero and a broken measurement degrades to "cycles are
/// microseconds" instead of taking the board down.
///
/// **Measured on QEMU: 1000 cycles/us**, against the 10 the old constant used.
/// So this does not merely fix hardware — every WCET and jitter figure this
/// tree has ever reported, including under QEMU, was **100x too large**. The
/// first version of this comment guessed that `rdcycle` would track the timer
/// under TCG and that nothing would move; booting it showed otherwise, which
/// is the only reason the number above is a measurement and not a second
/// guess. No gate scenario asserts an absolute WCET value, so the correction
/// changes no verdict — but any figure quoted from this path in a document
/// predates the fix and is wrong by that factor.
pub fn calibrate_cpu_freq() {
    let interval = crate::timebase::TIMER_FREQ / 100;
    let t0 = crate::timebase::now();
    let c0 = read_cycles();
    while crate::timebase::now().wrapping_sub(t0) < interval {
        core::hint::spin_loop();
    }
    let elapsed_us = (crate::timebase::now().wrapping_sub(t0))
        .saturating_mul(1_000_000) / crate::timebase::TIMER_FREQ.max(1);
    let cycles = read_cycles().wrapping_sub(c0);
    let ratio = if elapsed_us == 0 { 1 } else { (cycles / elapsed_us).max(1) };
    CYCLES_PER_US.store(ratio, core::sync::atomic::Ordering::Release);
}

/// Cycles per microsecond as measured, or 1 before calibration.
#[inline]
pub fn cycles_per_us() -> u64 {
    CYCLES_PER_US.load(core::sync::atomic::Ordering::Acquire).max(1)
}

/// Convert a cycle delta to microseconds.
#[inline]
pub fn cycles_to_us(cycles: u64) -> u64 {
    cycles / cycles_per_us()
}

// ── Public API ─────────────────────────────────────────────────────────────────

/// Begin a WCET measurement — returns current cycle count.
///
/// Call this immediately before the section to measure.
#[inline(always)]
pub fn wcet_begin() -> u64 {
    read_cycles()
}

/// End a WCET measurement and record the sample.
///
/// `point` — one of the `WCET_*` constants.
/// `start`  — value returned by the matching `wcet_begin()` call.
///
/// Returns the elapsed cycles.
#[inline]
pub fn wcet_end(point: u8, start: u64) -> u64 {
    let end = read_cycles();
    let elapsed = end.wrapping_sub(start);

    let idx = point as usize;
    if idx >= WCET_MAX_POINTS { return elapsed; }

    // Update min (atomically).
    let mut cur_min = WCET.min[idx].load(Ordering::Relaxed);
    while elapsed < cur_min {
        match WCET.min[idx].compare_exchange_weak(
            cur_min, elapsed, Ordering::Relaxed, Ordering::Relaxed)
        {
            Ok(_) => break,
            Err(v) => cur_min = v,
        }
    }

    // Update max (atomically).
    let mut cur_max = WCET.max[idx].load(Ordering::Relaxed);
    while elapsed > cur_max {
        match WCET.max[idx].compare_exchange_weak(
            cur_max, elapsed, Ordering::Relaxed, Ordering::Relaxed)
        {
            Ok(_) => break,
            Err(v) => cur_max = v,
        }
    }

    // Accumulate total and count (relaxed — statistics, not synchronisation).
    WCET.total[idx].fetch_add(elapsed, Ordering::Relaxed);
    WCET.count[idx].fetch_add(1, Ordering::Relaxed);

    // Check bound violation.
    let bound_us = WCET_BOUNDS_US[idx];
    if bound_us > 0 {
        let elapsed_us = cycles_to_us(elapsed);
        if elapsed_us > bound_us {
            WCET.violations[idx].fetch_add(1, Ordering::Relaxed);
            // Non-blocking print: try_acquire avoids spinning in ISR context.
            // Write directly to Uart (bypasses acquire) since we already hold the lock.
            if let Some(_guard) = crate::uart::try_acquire() {
                use core::fmt::Write;
                let _ = writeln!(crate::Uart,
                    "[WCET] VIOLATION: {} took {}µs > bound {}µs",
                    name_of(point), elapsed_us, bound_us
                );
            }
        }
    }

    elapsed
}

// ── Per-function instrumentation (RFC-0027) ─────────────────────────────────
//
// The `#[wcet(...)]` proc-macro emits calls to `wcet_begin_fn`/`wcet_end_fn`
// (NOT the fixed-point `wcet_begin`/`wcet_end`, which stay always-live for the
// 5 hand-instrumented points like timer_isr).
//
// These per-function wrappers are gated behind the `wcet` Cargo feature, which
// is OFF by default. Rationale: the per-function WCET CI gate was rejected
// (RFC-0027 §Results, KILL2) because under QEMU `-smp 4` TCG, `rdcycle` keeps
// advancing while the emulator time-slices to other harts, so a function's
// measured "elapsed" includes unrelated cross-hart work (347%-298,809% spread
// on a fixed binary). With the feature off, both wrappers are trivial no-ops
// that the optimiser eliminates — the annotations cost nothing in production.
// Enable on real hardware (VF2/K1) bring-up where `rdcycle` is trustworthy.

/// Per-function WCET measurement begin — feature-gated (see module note).
#[cfg(feature = "wcet")]
#[inline(always)]
pub fn wcet_begin_fn() -> u64 {
    wcet_begin()
}

/// No-op when the `wcet` feature is disabled (default). Returns 0; the matching
/// `wcet_end_fn` ignores the value, and the optimiser strips both calls.
#[cfg(not(feature = "wcet"))]
#[inline(always)]
pub fn wcet_begin_fn() -> u64 {
    0
}

/// Per-function WCET measurement end — feature-gated (see module note).
#[cfg(feature = "wcet")]
#[inline]
pub fn wcet_end_fn(point: u8, start: u64) -> u64 {
    wcet_end(point, start)
}

/// No-op when the `wcet` feature is disabled (default).
#[cfg(not(feature = "wcet"))]
#[inline(always)]
pub fn wcet_end_fn(_point: u8, _start: u64) -> u64 {
    0
}

/// Get a snapshot of statistics for one measurement point.
pub fn wcet_stats(point: u8) -> WcetStats {
    let idx = point as usize;
    if idx >= WCET_MAX_POINTS {
        return WcetStats::new();
    }
    WcetStats {
        min_cycles:   WCET.min[idx].load(Ordering::Relaxed),
        max_cycles:   WCET.max[idx].load(Ordering::Relaxed),
        total_cycles: WCET.total[idx].load(Ordering::Relaxed),
        count:        WCET.count[idx].load(Ordering::Relaxed),
        violations:   WCET.violations[idx].load(Ordering::Relaxed),
    }
}

/// Reset statistics for all measurement points.
pub fn wcet_reset_all() {
    for i in 0..WCET_MAX_POINTS {
        WCET.min[i].store(u64::MAX, Ordering::Relaxed);
        WCET.max[i].store(0, Ordering::Relaxed);
        WCET.total[i].store(0, Ordering::Relaxed);
        WCET.count[i].store(0, Ordering::Relaxed);
        WCET.violations[i].store(0, Ordering::Relaxed);
    }
}

/// Print a WCET report table to UART.
pub fn wcet_report() {
    crate::kconsoleln!("[WCET] ── Execution Time Report ────────────────────────────────────");
    crate::kconsoleln!("[WCET]  {:16} {:>10} {:>10} {:>10} {:>7} {:>6}",
        "name", "min_us", "max_us", "avg_us", "count", "viol");
    for i in 0..WCET_MAX_POINTS {
        let count = WCET.count[i].load(Ordering::Relaxed);
        if count == 0 { continue; }
        let min_c  = WCET.min[i].load(Ordering::Relaxed);
        let max_c  = WCET.max[i].load(Ordering::Relaxed);
        let total  = WCET.total[i].load(Ordering::Relaxed);
        let avg_c  = total / count;
        let viol   = WCET.violations[i].load(Ordering::Relaxed);

        let min_us = cycles_to_us(min_c);
        let max_us = cycles_to_us(max_c);
        let avg_us = cycles_to_us(avg_c);

        crate::kconsoleln!("[WCET]  {:16} {:>10} {:>10} {:>10} {:>7} {:>6}",
            name_of(i as u8), min_us, max_us, avg_us, count, viol);
    }
    crate::kconsoleln!("[WCET] ────────────────────────────────────────────────────────────");
}

/// Check all bounds and log any points that have recorded violations.
///
/// Returns the number of points with at least one violation.
pub fn wcet_check_bounds() -> usize {
    let mut total_violations = 0usize;
    for i in 0..WCET_MAX_POINTS {
        let viol = WCET.violations[i].load(Ordering::Relaxed);
        if viol > 0 {
            let max_c  = WCET.max[i].load(Ordering::Relaxed);
            let max_us = cycles_to_us(max_c);
            let bound  = WCET_BOUNDS_US[i];
            crate::kwarn!(
                "[WCET] BOUND EXCEEDED: {} max={}µs bound={}µs violations={}",
                name_of(i as u8), max_us, bound, viol
            );
            total_violations += 1;
        }
    }
    total_violations
}

// ── F16.4: Jitter measurement ─────────────────────────────────────────────────
//
// Measures the interval between successive events (e.g., timer ISR fires)
// to characterise scheduling jitter.

/// Maximum number of jitter measurement series.
pub const JITTER_MAX_SERIES: usize = 4;

/// Jitter series ID: timer ISR interval.
pub const JITTER_TIMER_ISR:     u8 = 0;
/// Jitter series ID: ISR → actuator write latency.
pub const JITTER_ISR_TO_ACT:    u8 = 1;

/// Number of harts tracked for per-hart jitter delta computation.
///
/// Mirrors the platform's `NUM_CPUS` (QEMU virt/VF2 = 4, K1 = 8). Sized
/// per-platform rather than hardcoded so `last` never silently drops samples
/// from a hart the running config actually has.
const JITTER_MAX_HARTS: usize = azos_drv_base::platform::hw::NUM_CPUS;

struct JitterTable {
    /// Previous cycle reading, keyed by `[hart_id][series]` — **not** shared
    /// across harts. `rdcycle` is a per-hart CSR (RISC-V priv spec never
    /// guarantees it's synchronised between harts, and under QEMU TCG the
    /// per-hart counters can be offset from one another arbitrarily — see
    /// `read_cycles` docs above). `jitter_record` runs from the timer ISR on
    /// every hart; comparing "now" read by one hart against a "last" value
    /// swapped in by a *different* hart produces a delta that means nothing.
    /// Keying by hart id keeps every comparison same-hart, where `rdcycle`
    /// is genuinely monotonic and successive fires are thousands of cycles
    /// apart — never 0, never backwards.
    last:       [[AtomicU64; JITTER_MAX_SERIES]; JITTER_MAX_HARTS],
    min_delta:  [AtomicU64; JITTER_MAX_SERIES],
    max_delta:  [AtomicU64; JITTER_MAX_SERIES],
    count:      [AtomicU64; JITTER_MAX_SERIES],
}

static JITTER: JitterTable = JitterTable {
    last:      [const { [const { AtomicU64::new(0) }; JITTER_MAX_SERIES] }; JITTER_MAX_HARTS],
    min_delta: [const { AtomicU64::new(u64::MAX) }; JITTER_MAX_SERIES],
    max_delta: [const { AtomicU64::new(0) };        JITTER_MAX_SERIES],
    count:     [const { AtomicU64::new(0) };        JITTER_MAX_SERIES],
};

/// Record one jitter observation (call each time the event fires).
///
/// `series` — one of the `JITTER_*` constants.
pub fn jitter_record(series: u8) {
    let idx = series as usize;
    if idx >= JITTER_MAX_SERIES { return; }

    // See `JitterTable::last` doc comment: comparisons must stay same-hart.
    let hart = azos_arch::cpu::hart_id();
    if hart >= JITTER_MAX_HARTS { return; } // defensive: unexpected hart id

    let now = read_cycles();
    let prev = JITTER.last[hart][idx].swap(now, Ordering::Relaxed);

    if prev == 0 { return; } // first sample on this hart/series — no delta yet
    if now < prev { return; } // non-monotonic same-hart reading — discard, don't clamp

    let delta = now - prev;

    let mut cur_min = JITTER.min_delta[idx].load(Ordering::Relaxed);
    while delta < cur_min {
        match JITTER.min_delta[idx].compare_exchange_weak(
            cur_min, delta, Ordering::Relaxed, Ordering::Relaxed)
        {
            Ok(_) => break,
            Err(v) => cur_min = v,
        }
    }

    let mut cur_max = JITTER.max_delta[idx].load(Ordering::Relaxed);
    while delta > cur_max {
        match JITTER.max_delta[idx].compare_exchange_weak(
            cur_max, delta, Ordering::Relaxed, Ordering::Relaxed)
        {
            Ok(_) => break,
            Err(v) => cur_max = v,
        }
    }

    JITTER.count[idx].fetch_add(1, Ordering::Relaxed);
}

/// Print a jitter report to UART.
pub fn jitter_report() {
    /// Nanoseconds per second — used to convert a cycle delta to ns.
    const NS_PER_SEC: u64 = 1_000_000_000;

    const NAMES: [&str; JITTER_MAX_SERIES] = [
        "timer_isr", "isr_to_act", "unused_2", "unused_3"
    ];

    crate::kconsoleln!("[JITTER] ── Jitter Report ──────────────────────────────────────────");
    crate::kconsoleln!("[JITTER]  {:12} {:>12} {:>12} {:>10}",
        "series", "min_ns", "max_ns", "samples");

    // Cycles per second, from the measurement rather than the timer clock —
    // the jitter report had the same wrong denominator as `cycles_to_us`.
    let freq = cycles_per_us().saturating_mul(1_000_000);
    for i in 0..JITTER_MAX_SERIES {
        let count = JITTER.count[i].load(Ordering::Relaxed);
        if count == 0 { continue; }

        let min_c = JITTER.min_delta[i].load(Ordering::Relaxed);
        let max_c = JITTER.max_delta[i].load(Ordering::Relaxed);

        // Convert cycles → nanoseconds: ns = cycles * NS_PER_SEC / freq.
        // `jitter_record` now only ever diffs same-hart, monotonic `rdcycle`
        // readings (see `JitterTable::last` doc comment), so `delta` should
        // stay small (thousands of cycles). `saturating_mul` is defense in
        // depth only — it keeps a future regression from panicking on
        // overflow instead of silently re-introducing the old absurd-max
        // symptom; it is not expected to trigger in normal operation.
        let min_ns = if freq > 0 { min_c.saturating_mul(NS_PER_SEC) / freq } else { 0 };
        let max_ns = if freq > 0 { max_c.saturating_mul(NS_PER_SEC) / freq } else { 0 };

        crate::kconsoleln!("[JITTER]  {:12} {:>12} {:>12} {:>10}",
            NAMES[i], min_ns, max_ns, count);
    }
    crate::kconsoleln!("[JITTER] ────────────────────────────────────────────────────────────");
}
