#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0 OR GPL-2.0-only
# SPDX-FileCopyrightText: 2026 Fernando Rodriguez
"""Write the SHA-256 of every ELF the disk image ships, keyed by its FAT32 name.

    python3 userspace/image_hashes.py build/image_hashes.rs HELLO.ELF=build/hello.elf ...

The output is Rust, `include!`d by `crates/core/sched/src/seccomp.rs`: the kernel binds
each seccomp image profile to the digest of the exact bytes the Makefile copies
onto the image, not to the file name those bytes are copied under.

The file is rewritten only when its contents change, so a `make` that rebuilt
nothing leaves its mtime alone and cargo does not recompile the kernel.
"""

import hashlib
import os
import re
import sys


def check(table_path, pairs):
    """Exit non-zero unless every NAME=path has the digest the table lists.

    For a gate scenario that deletes and rebuilds an ELF after the kernel was
    built: a rebuilt image whose bytes differ from the table would be refused at
    boot, which reads like a kernel fault. This says which image and why, before
    anything boots.
    """
    text = open(table_path, encoding="utf-8").read()
    table = {}
    for m in re.finditer(r'\("([A-Z0-9_]+\.ELF)", \[([^\]]*)\]\)', text):
        table[m.group(1)] = bytes(int(b, 16) for b in m.group(2).split(","))
    mismatches = 0
    for pair in pairs:
        name, sep, path = pair.partition("=")
        if not sep or not name or not path:
            sys.exit(f"image_hashes.py: expected NAME=path, got {pair!r}")
        with open(path, "rb") as f:
            digest = hashlib.sha256(f.read()).digest()
        if table.get(name) != digest:
            listed = table[name].hex()[:16] + "..." if name in table else "no entry"
            print(f"image_hashes.py: {name} ({path}) is sha256 {digest.hex()[:16]}..., "
                  f"{table_path} lists {listed}")
            mismatches += 1
    sys.exit(1 if mismatches else 0)


def main(argv):
    if len(argv) >= 2 and argv[1] == "--check":
        if len(argv) < 4:
            sys.exit("usage: image_hashes.py --check <table.rs> NAME=path.elf ...")
        check(argv[2], argv[3:])
    # RFC-0047: `--const NAME` names the table (default IMAGE_SHA256) and
    # `--skip-missing` leaves out a NAME=path whose file was not built: the
    # third-party table (`build/thirdparty_hashes.rs`) lists BusyBox only when
    # `make busybox` has built it, and is an empty table otherwise.
    const = "IMAGE_SHA256"
    skip_missing = False
    while len(argv) > 1 and argv[1].startswith("--"):
        if argv[1] == "--const" and len(argv) > 2:
            const = argv[2]
            argv = argv[:1] + argv[3:]
        elif argv[1] == "--skip-missing":
            skip_missing = True
            argv = argv[:1] + argv[2:]
        else:
            sys.exit(f"image_hashes.py: unknown option {argv[1]}")
    if len(argv) < 3 and not skip_missing:
        sys.exit("usage: image_hashes.py [--const NAME] [--skip-missing] <out.rs> NAME=path.elf ...")
    out = argv[1]
    rows = []
    seen = set()
    for pair in argv[2:]:
        name, sep, path = pair.partition("=")
        if not sep or not name or not path:
            sys.exit(f"image_hashes.py: expected NAME=path, got {pair!r}")
        if name in seen:
            sys.exit(f"image_hashes.py: {name} is listed twice")
        seen.add(name)
        if skip_missing and not os.path.isfile(path):
            continue
        with open(path, "rb") as f:
            digest = hashlib.sha256(f.read()).digest()
        rows.append((name, path, digest))

    lines = [
        "// Generated by userspace/image_hashes.py from the ELFs the Makefile copies",
        "// onto the disk image. Do not edit: `make build/image_hashes.rs` rewrites it.",
        "",
        "/// `(name on the FAT32 image, SHA-256 of the ELF copied under that name)`,",
        "/// in Makefile copy order.",
        f"pub const {const}: &[(&str, [u8; 32])] = &[",
    ]
    for name, path, digest in rows:
        lines.append(f"    // {path}")
        body = ", ".join(f"0x{b:02x}" for b in digest)
        lines.append(f'    ("{name}", [{body}]),')
    lines.append("];")
    text = "\n".join(lines) + "\n"

    try:
        with open(out, "r", encoding="utf-8") as f:
            if f.read() == text:
                return
    except FileNotFoundError:
        pass
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    tmp = out + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(text)
    os.replace(tmp, out)


if __name__ == "__main__":
    main(sys.argv)
